spring.application.name=gateway-service

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/shop

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.urls[0].name=Product Service
springdoc.swagger-ui.urls[0].url=/aggregate/product-service/v3/api-docs

server.port=9000